name: Upload OpenAPI spec to Stainless

on:
  workflow_run:
    workflows: ["sst"]
    types:
      - completed
    branches:
      - production
  workflow_dispatch:

jobs:
  stainless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl https://openapi.terminal.shop/doc > openapi.json
        
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'openapi.json'
          config_path: 'stainless.yml'
          project_name: 'terminal'
